name: "CI"

on:
  push:
    branches:
      - "master"
  pull_request: null

jobs:
  qa:
    name: "QA"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        php-version: ["8.0"]
        os: [ubuntu-latest]
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3.5.2"

      - name: "Set up PHP"
        uses: "shivammathur/setup-php@2.25.1"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          tools: "phive"

      - name: "Install dependencies"
        run: |
          composer install --no-interaction --optimize-autoloader --prefer-dist
          ant install-tools

      - name: "Run PHP CS Fixer"
        run: "ant php-cs-fixer"

      - name: "Run Psalm"
        run: "ant psalm"

  tests:
    name: "Tests"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        php-versions: ["7.2", "7.3", "7.4", "8.0", "8.1", "8.2"]
        os: [ubuntu-latest]

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3.5.2"

      - name: "Set up PHP"
        uses: "shivammathur/setup-php@2.25.1"
        with:
          php-version: "${{ matrix.php-versions }}"
          coverage: "pcov"
          extensions: mbstring
          ini-values: "display_errors=On, memory_limit=2G"

      - name: "Install dependencies"
        run: composer install --no-interaction --optimize-autoloader --prefer-dist

      - name: "Run PHPUnit tests"
        run: tools/phpunit --coverage-clover build/logs/clover.xml

      - name: "Send code coverage report"
        uses: codecov/codecov-action@v3.1.4
        with:
          files: "build/logs/clover.xml"
